default:
  image: duskmoon/dev-env:ucore-ci

stages:
  - test

test-code-job:
  stage: test
  script:
    - git clone https://token:${UCORE_CHECKER_REPO_READ_TOKEN}@git.tsinghua.edu.cn/os-lab/ta-2022a/ucore-tutorial-checker-2022a.git ucore-tutorial-ci
    - git clone https://token:${UCORE_TEST_REPO_READ_TOKEN}@git.tsinghua.edu.cn/os-lab/public/ucore-tutorial-test-2022a.git ucore-tutorial-ci/workplace/user
    - cd ucore-tutorial-ci && make test CHAPTER=`echo $CI_COMMIT_REF_NAME | grep -oP 'ch\K[0-9]'`
